---
title: "Cleaning Script"
author: "Douglas Lunnie"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
#Install/Load Packages
#install.packages("tidyverse")
#install.packages("readxl")
#install.packages("sqldf")

rm(list=ls()) #Remove all objects in environment

library(sqldf)
library(tidyverse)
library(tibble)
library(readxl)

#Programming Note: Opportunity to refresh/load all packages to avoid commenting out install commands?

```

```{r, include=FALSE, warning = FALSE}
#Load data into environment. 
#Requires manually renaming raw diary files to the indicated "Raw_diary" listed below. Files must be read from the same directory as this code. 
#Ensure Raw .csv files should be encoded as UTF-8, this can be done via opening the .csv in Notepad>Save As> ... Select UTF-8 encoding and overwrite file.
#Some systems automatically reformat .csv files when opened in Excel. 

#Programming note - Opportunity to have the script reformat the code on read-in. 


demo_names <- read.csv("demo_names.csv")
diary_names <-read.csv("diary_names.csv")


raw_demo <- read_xlsx("Laundry Room Diary Datafile 52 wks ending 10.16.22.xlsx", sheet = "Demos and Segment")


raw_diary <- read_xlsx("Laundry Room Diary Datafile 52 wks ending 10.16.22.xlsx", sheet = "Diary 10.18.21 to 10.16.22")

```


```{r, include=FALSE}
#Rename Diary+Demo Files According to new  name set

diary <- raw_diary #simplify name

colnames(diary) <-  colnames(diary_names) #overwrite names to simplify review
colnames(diary)

demo <- raw_demo

colnames(demo) <- colnames(demo_names)
colnames(demo)
```



```{r}
# Re-lcassify per capita income categories to be more consistent. - Gabriella
per_cap = sqldf("SELECT CASE WHEN income_HOH in ('Under $25k per year', '$25,000 to $49,999 per year') THEN 'Low Income'
WHEN income_HOH in ('$50,000 to $69,999 per year', '$70,000 to $99,999 per year') THEN 'Middle Income'
WHEN income_hoh = '$100,000 per year or higher' then 'Upper Income' ELSE NULL END AS per_cap2
FROM demo")

#replace with the new column
demo$per_cap = per_cap$per_cap2
```




```{r, include=FALSE}
#remove raw d"f's from environment
rm(raw_demo, raw_diary, demo_names, diary_names, per_cap)
```



#Intermediate Cleaning Steps


```{r}
# Order age_HOH logically
demo["age_HOH"][demo["age_HOH"] == "Under 25 Years"] <- "(1) Under 25"
demo["age_HOH"][demo["age_HOH"] == "25-29 Years"] <- "(2) 25-29"
demo["age_HOH"][demo["age_HOH"] == "30-34 Years"] <- "(3) 30-34"
demo["age_HOH"][demo["age_HOH"] == "35-39 Years"] <- "(4) 35-39"
demo["age_HOH"][demo["age_HOH"] == "40-44 Years"] <- "(5) 40-44"
demo["age_HOH"][demo["age_HOH"] == "45-49 Years"] <- "(6) 45-49"
demo["age_HOH"][demo["age_HOH"] == "50-54 Years"] <- "(7) 50-54"
demo["age_HOH"][demo["age_HOH"] == "55-64 Years"] <- "(8) 55-64"
demo["age_HOH"][demo["age_HOH"] == "65+ Years"]   <- "(9) Over 65"


table(demo$age_HOH)

```

```{r, include = FALSE}
#replace demo respondent age
demo["respondent_age"][demo["respondent_age"] == "Over 80"]  <-  "89"
demo$respondent_age <- as.numeric(demo$respondent_age)

#class(demo$respondent_age) - Check for accuracy and comment out
#hist(demo$respondent_age)
```


```{r}

#replace segment typo
demo["segment"][demo["segment"] == "PASSSIONATE OPTIMIZER"]  <-  "PASSIONATE OPTIMIZERS"
table(demo$segment)

```




```{r}
#replacee other adults respondent age over 80 and save as numeric data
for (i in 35:43){  #For all adults, recode "Over 80" as 89
  demo[i][demo[i] == "Over 80"] <- "89" 
   demo[i] <- as.numeric(unlist(demo[i]))  #Use unlist function to perform loop on list type call
   #(https://www.statology.org/r-list-object-cannot-be-coerced-to-type-double/)
}
rm(i)  #remove i variable after completed loop
#mean(demo$adult_age5, na.rm = TRUE)
#hist(demo$adult_age5) # Check but commented out

```


```{r, include=FALSE}
demo["child_count"][demo["child_count"] == "None"]  <-  "0"
demo$child_count <- as.numeric(demo$child_count)

class(demo$child_count) #Check for accuracty and comment out
#hist(demo$child_count)
```

```{r, include=FALSE}
#Experiment with methods of selecting numerics from strings

table(demo$child1_age)
demo$child1_age[18] #"16 Years Old
demo$child1_age[343] #"Less than 1 Year old


str_extract(demo$child1_age, c("\\d+")) #Select entries containing one or more digits. Will return less than one year old as "1".

#NOTE: Current regex for child age status removes sensitivity to newborns

sum(str_count(demo$child1_age, "Less than"), na.rm = TRUE)

```

```{r, include=FALSE}
#Take all children's ages, written in strings, and rewrite as numeric for analysis. Tried to do this in a loop but couldn;'t get the indexing right. Children under 1 will be counted as 1yo's. 

demo$child1_age <- as.numeric(str_extract(demo$child1_age, "\\d+"))
demo$child2_age <- as.numeric(str_extract(demo$child2_age, "\\d+"))
demo$child3_age <- as.numeric(str_extract(demo$child3_age, "\\d+"))
demo$child4_age <- as.numeric(str_extract(demo$child4_age, "\\d+"))
demo$child5_age <- as.numeric(str_extract(demo$child5_age, "\\d+"))
demo$child6_age <- as.numeric(str_extract(demo$child6_age, "\\d+"))
demo$child7_age <- as.numeric(str_extract(demo$child7_age, "\\d+"))
demo$child8_age <- as.numeric(str_extract(demo$child8_age, "\\d+"))
demo$child9_age <- as.numeric(str_extract(demo$child9_age, "\\d+"))
demo$child10_age <- as.numeric(str_extract(demo$child10_age, "\\d+"))


mean(demo$child1_age, na.rm = TRUE)


demo[, 153:162] #confirm column counts for child ages
```


```{r}
#Explore Retailer "Others"

#table(diary$Grocery_Other)

diary$Grocery_Other <-  str_to_lower(diary$Grocery_Other) #move all to lowercase to aid regexes

diary$Grocery_Other <- str_replace(diary$Grocery_Other, c("acme.+", "acme\\s", "acme"), "acme")



#for (i in 1:length(diary$Grocery_Other)){print(i)}



#diary$Grocery_Other <- str_replace(diary$Grocery_Other, "aldi." , "aldi") 




#table(str_extract(diary$Grocery_Other, "Aldi"))

```



CLean out duplicate entries in demo
```{r}
demo_unique <- distinct(demo, respondent_id,.keep_all = TRUE)

```

```{r, include=false}
#write combined files to new CSVs
write.csv(demo, "demographics.csv", row.names = FALSE)
write.csv(diary, "diary.csv", row.names = FALSE)
write.csv(demo_unique, "demo_unique.csv", row.names = FALSE)

```



