---
title: "Lunnie Combine Data"
author: "Douglas Lunnie"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tibble)
```



```{r}
#Load data into environment

Demo1 <- read.csv("../Data/Demo_1.csv") #read in first demographic set
Demo2 <- read.csv("../Data/Demo_2.csv") #2nd demographic set

Diary1 <-read.csv("../Data/Diary_1.csv")#1st Diary Set
Diary2 <-read.csv("../Data/Diary_2.csv")#2nd Diary Set

Diary1 <- tibble(Diary1)
Diary2 <- tibble(Diary2)
```




```{r}
demo <- rbind(Demo1, Demo2) #Combine both demographic datasets into one dataframe
```

```{r}
# diary <- rbind(Diary1, Diary2) # Commented out: this throws an error since the diary DFs are not identical columns.
```


```{r}
#Explore the differences in the columns

#First unlike column is 1.43 = "12. How would you best describe the type of cleaning? (Select one)"

table(Diary1[,43])
```


```{r}
# Dropdown categories from Diary1 and Diary2 are not different. Only the name of the question changed to: "12. What colors of fabric were in this load? (Select one)
# This column may be renamed without issue. 
table(Diary2[,43])
```

```{r}
#Check Each Column Name
colnames(Diary1[43])
colnames(Diary2[43])

#rename to common item using 2nd more descriptive name -
# Note the colnames(df)[NN] syntax here was confusing. Rename by index.
colnames(Diary1)[43] <-  colnames(Diary2)[43]

#Test that they are now the same
colnames(Diary1[43]) == colnames(Diary2[43])

```

```{r}
colnames(Diary1[44])
colnames(Diary2[44])
```


```{r}
table(Diary1[44])
```

```{r}
table(Diary2[44]) #not wildly different form the first results set. I think these can be combined. 
```
```{r}
#rename to common item using 2nd more descriptive name -
# Note the colnames(df)[NN] syntax here was confusing. Rename by index.
colnames(Diary1)[44] <-  colnames(Diary2)[44]

#Test that they are now the same
colnames(Diary1[44]) == colnames(Diary2[44])

```

```{r}
#Next column set is d2.50 + d2.51. These questions were added and column names for these should be inserted in the same place for d1.50 and d1.51. 
colnames(Diary2[50])

Diary1 <- add_column(Diary1, 'NA', .after = 49) #Cannot directly add variable driven by indexing Diary2[50], the names adds a "/" at each end of the string. Adding a placeholder

colnames(Diary1)[50] <-  colnames(Diary2)[50] #renaming via indexing. OVerwrite the placeholder name

#Check the names are the same
colnames(Diary1[50]) ==  colnames(Diary2[50])
```

```{r}
# Perform the same excercise for column d2.51

colnames(Diary2[51])

Diary1 <- add_column(Diary1, 'NA', .after = 50) #Cannot directly add variable driven by indexing Diary2[50], the names adds a "/" at each end of the string. Adding a placeholder

colnames(Diary1)[51] <-  colnames(Diary2)[51] #renaming via indexing. OVerwrite the placeholder name

#Check the names are the same
colnames(Diary1[51]) ==  colnames(Diary2[51])

```

```{r}
#Add four new columns at the end
lastnames <- c(colnames(Diary2[222:225]))

#Diary1 <- add_column(Diary1, lastnames)

for (i in 1:length(lastnames)){ #set loop length
  n = 221 + i       #Set Starting Index
  print (n)   #Print Iterate
  Diary1 <- add_column(Diary1, "NA") # Add new column
  colnames(Diary1)[n] <-  colnames(Diary2)[n] #rename Column
  }
# Check to confirm all names are identical
colnames(Diary2[222:225]) == colnames(Diary1[222:225])
```

```{r}
#Combine diaries together now that columns agree
diary <- rbind(Diary1, Diary2)

```


```{r}
#Rename Diary Files According to new  name set
names <- read.csv("../Data/diary_names.csv")
colnames(diary) <-  colnames(names)
colnames(diary)

```


```{r}
#write combined files to new CSVs

write.csv(demo, "../data\\demographics.csv", row.names = FALSE)
write.csv(diary, "../data\\diary.csv", row.names = FALSE)
```

